#!/usr/bin/env bash

function show_help {
echo -e "Usage:\t$0 [-U user] [-H host] [-P printer] [-C count] [-N pages_on_paper] [-O orientation] [-K duplex] [-S papersize] files"
echo -e "\t$0 -h"
echo ""
echo "Prints File on printer printer as user user logging in on host host"
}

if [ -f ${HOME}/.config/uniprint.conf ]; then
	source ${HOME}/.config/uniprint.conf
elif [ -f /etc/uniprint.conf ]; then
	source /etc/uniprint.conf
else
	echo 'No uniprint.conf! Please use `cp /usr/share/uniprint/example.conf ~/.config/uniprint.conf` and adjust this file for your needs.'
	exit 1
fi

while getopts "U:P:H:C:N:K:S:O:h" opt; do
	case $opt in
		O)
			ORIENTATION=$OPTARG
			;;
		U)
			UNIUSER=$OPTARG
			;;
		P)
			UNIPRINTER=$OPTARG
			;;
		H)
			UNIHOST=$OPTARG
			;;
		C)
			COUNT=$OPTARG
			;;
		N)
			PAGES=$OPTARG
			;;
		K)
			DUPLEX=$OPTARG
			;;
		S)
			PAPERSIZE=$OPTARG
			;;
		h)
			show_help
			exit 1
			;;
	esac
done

shift $((OPTIND-1))
if [ -z "${UNIUSER}" ]; then
	echo "No username provided!"
	exit 1
fi

if [ -z "$UNIHOST" ]; then
	echo "No SSH-Host provided!"
	exit 1
fi

if [ -z "$UNIPRINTER" ]; then
	echo "No printer provided!"
	exit 1
fi

if [ -z "$ORIENTATION" ]; then
	ORIENTATION=portrait
fi

if [ -z "$DUPLEX" ]; then
	DUPLEX=simplex
fi

if [ -z "$PAGES" ]; then
	PAGES=0
fi

if [ -z "$COUNT" ]; then
	COUNT=1
fi

if [ -z "$PAPERSIZE" ]; then
	PAPERSIZE="a4w"
fi

ADDITIONALOPTIONS="-N${PAGES} -#${COUNT} -K${DUPLEX} -O${ORIENTATION} -F${PAPERSIZE}"

FILES=$@

if [ -z "${FILES}" ]; then
	echo "No files provided. Printing from stdin"
	exec ssh $UNIUSER@$UNIHOST "lpr -P ${UNIPRINTER} ${UNIOPTIONS} ${ADDITIONALOPTIONS}"
fi

for FILE in ${FILES}
do
	echo "Printing ${FILE} on ${UNIPRINTER} as ${UNIUSER}@${UNIHOST}"
	cat ${FILE} | ssh $UNIUSER@$UNIHOST "lpr -P ${UNIPRINTER} ${UNIOPTIONS} ${ADDITIONALOPTIONS}"
	exit
done
